services:
  - type: web
    name: ardiva
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: APPS_SCRIPT_URL
        sync: false
      - key: SECRET_TOKEN
        sync: false
